name: "Setup hserver"
description: "Setup hserver to point to the specified server."
branding:
  icon: "arrow-up-right"
  color: "orange"

inputs:
  server:
    description: "The hserver host string(s)."

  client_id:
    description: "Optional SideFX Web API client_id value to use."

  client_secret_key:
    description: "Optional SideFX Web API client_secret_key value to use."

  extra:
    description: "Optional extra command flags to pass to the hserver command."

  skip_validation:
    description: "Skip credential validation check when using login licensing."
    required: false
    default: "0"

runs:
  using: "composite"

  steps:
    - if: inputs.server == ''
      run: echo server is empty && exit 1
      shell: bash

    - name: Setup hserver
      run: hserver ${{ inputs.client_id != '' && format('--clientid {0}', inputs.client_id) || '' }} ${{ inputs.client_secret_key != '' && format('--clientsecret {0}', inputs.client_secret_key) || '' }} --host ${{ inputs.server }} ${{ inputs.extra || '' }}
      shell: bash

    - if: inputs.client_id != '' && inputs.client_secret_key != '' && inputs.skip_validation != '1'
      name: Check credentials if using login licensing
      run: timeout 4 sesictrl login > /dev/null
      shell: bash
