# Execute repository tests.
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        houdini-version:
          - "19.5"  # Python 3.9
          - "20.0"  # Python 3.10
          - "20.5"  # Python 3.11

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup hserver
        uses: ./
        with:
          server: ${{ secrets.LICENSE_SERVER }}
          client_id: ${{ secrets.SESI_CLIENT_ID }}
          client_secret_key: ${{ secrets.SESI_CLIENT_SECRET }}

      # Grep for the license server url in the 'hserver -l' output to ensure it's pointed correctly.
      - name: Test hserver is correctly pointed
        run: hserver -l | grep ${{ secrets.LICENSE_SERVER }}
        shell: bash

      - name: Stop running hserver
        run: hserver -q
        shell: bash

      - name: Test when the credentials are bad and the validation should fail.
        id: catch-failure
        uses: ./
        continue-on-error: true
        with:
          server: ${{ secrets.LICENSE_SERVER }}
          client_id: foo
          client_secret_key: bar

      - name: Validate previous failure
        if: steps.catch-failure.outcome == 'success'
        run: exit 1

      - name: Stop running hserver
        run: hserver -q
        shell: bash

      - name: Test when the credentials are bad and validation is disabled.
        uses: ./
        with:
          server: ${{ secrets.LICENSE_SERVER }}
          client_id: foo
          client_secret_key: bar
          skip-validation: 1
